---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify: check_reboot

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: yes