---
- name: Build elmobot
  ansible.builtin.script:
  cmd: /home/ubuntu/elmobot/build.sh
- name: Restart elmobot
  ansible.builtin.systemd_service:
  name: elmobot.service
  state: reloaded
  scope: user
