---
- name: Build elmobot
  ansible.builtin.command:
    cmd: ./build.sh
    chdir: /home/ubuntu/elmobot

- name: Restart elmobot
  ansible.builtin.systemd_service:
    name: elmobot.service
    state: restarted
    scope: user
