---
- name: Build and restart elmobot
  block:
    - name: Build elmobot
      ansible.builtin.script:
        cmd: /home/ubuntu/elmobot/build.sh
    - name: Restart elmobot user service
      ansible.builtin.systemd_service:
        name: elmobot.service
        state: reloaded
        scope: user
